name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17

      - name: Build
        run: make install
        
      - name: Test
        run: make test

      - name: Gosec check
        run: make check
      
      - name: Lint check
        run: make lint
